itswael/GatorCan

- gatorcan-backend/utils/gentoken.go
- gatorcan-backend/utils/jwt.go
> implemented JWT token generation #40

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/main.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/tests/test_setup.go
- gatorcan-backend/tests/user_details_test.go
- gatorcan-backend/tests/user_registration_test.go
> #issue9: Implemented Fetch User Details Api and unit tests

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/go.mod
- gatorcan-backend/main.go
- gatorcan-backend/tests/user_registration_test.go
- gatorcan-backend/utils/validateemail.go
> Implemented fetch user details

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/tests/test_setup.go
- gatorcan-backend/tests/user_deletion_test.go
- gatorcan-backend/tests/user_registration_test.go
- gatorcan-backend/tests/user_update_test.go
> #issue62: Implemented user update and roles update

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/main.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/tests/test_setup.go
- gatorcan-backend/tests/user_deletion_test.go
- gatorcan-backend/tests/user_details_test.go
- gatorcan-backend/tests/user_registration_test.go
- gatorcan-backend/tests/user_update_test.go
> #Issue62: Implemented User details updating and deletion 

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/tests/test_setup.go
- gatorcan-backend/tests/user_login_test.go
> #issue42  write unit tests for authentication flow

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/models/role.go
- gatorcan-backend/models/user.go
- gatorcan-backend/models/userRoles.go
- gatorcan-backend/repositories/userRepository.go
> #issue12  define roles

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/go.mod
- gatorcan-backend/main.go
- gatorcan-backend/tests/user_registration_test.go
- gatorcan-backend/utils/validateemail.go
> Define user roles (Admin, Instructor, Student, Teaching Assistant) #12

- gatorcan-frontend/package-lock.json
- gatorcan-frontend/package.json
- gatorcan-frontend/src/App.css
- gatorcan-frontend/src/App.jsx
- gatorcan-frontend/src/components/AdminDashboard.jsx
- gatorcan-frontend/src/components/InstructorDashboard.jsx
- gatorcan-frontend/src/components/Login.jsx
- gatorcan-frontend/src/components/Login.test.jsx
- gatorcan-frontend/src/components/ProtectedDashboard.jsx
- gatorcan-frontend/src/components/ProtectedRoute.jsx
- gatorcan-frontend/src/components/StudentDashboard.jsx
- gatorcan-frontend/src/index.css
- gatorcan-frontend/src/main.jsx
- gatorcan-frontend/src/services/AuthService.jsx
> Feature/login api with react UI

- Sprint1.md
- gatorcan-backend/controllers/userController.go
- gatorcan-backend/main.go
- gatorcan-backend/middleware/auth_middleware.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/utils/logger.go
> implemented logging for sprint one issues

- gatorcan-backend/DTOs/courseDTOs.go
- gatorcan-backend/controllers/courseController.go
- gatorcan-backend/controllers/userController.go
- gatorcan-backend/models/activeCourse.go
- gatorcan-backend/models/enrollment.go
- gatorcan-backend/repositories/coursesRepository.go
- gatorcan-backend/repositories/userRepository.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/services/courseService.go
> implemented: controller, services and repository for courses

- gatorcan-backend/controllers/courseController_test.go
- gatorcan-backend/tests/role_based_access_test.go
- gatorcan-backend/tests/test_setup.go
> #issue111: implemented test cases for fetching enrolled courses. 

- gatorcan-frontend/src/components/StudentCourses.jsx
> #issue 117

- gatorcan-frontend/src/components/StudentCourses.jsx
- gatorcan-frontend/src/services/CourseService.jsx
#123 
#124 
#125 
#128 
#129 
#127
> Issue 127: integrate course fetching backend

- gatorcan-frontend/.babelrc
- gatorcan-frontend/cypress/e2e/protectedDashboard.cy.js
- gatorcan-frontend/jest.config.js
- gatorcan-frontend/jest.setup.js
- gatorcan-frontend/package-lock.json
- gatorcan-frontend/package.json
- gatorcan-frontend/src/components/Login.jsx
- gatorcan-frontend/src/components/StudentNavbar.jsx
- gatorcan-frontend/src/components/StudentNavbar.test.jsx
- gatorcan-frontend/src/services/AdminService.test.jsx
- gatorcan-frontend/src/services/AuthService.test.jsx
- gatorcan-frontend/src/services/CourseService.test.jsx
> Issue 126: UI test cases

- gatorcan-backend/config/config.go
- gatorcan-backend/controllers/courseController.go
- gatorcan-backend/controllers/userController.go
- gatorcan-backend/database/db.go
- gatorcan-backend/go.mod
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/main.go
- gatorcan-backend/repositories/coursesRepository.go
- gatorcan-backend/repositories/roleRepository.go
- gatorcan-backend/repositories/userRepository.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/services/courseService.go
- gatorcan-backend/services/userService.go
fixes #223 #224 #225 #226 #227
> Implement Interfaces and Dependency Injection #223

- gatorcan-backend/controllers/courseController.go
- gatorcan-backend/errors/databaseErrors.go
- gatorcan-backend/services/courseService.go
- gatorcan-backend/unit_tests/courseController_test.go
- gatorcan-backend/unit_tests/courseService_test.go
- gatorcan-backend/unit_tests/mocks/repositories.go
- gatorcan-backend/unit_tests/mocks/services.go
- gatorcan-backend/unit_tests/userController_test.go
- gatorcan-backend/unit_tests/userService_test.go
> added mock repositories and services and fixed the unit tests

- gatorcan-backend/main.go
- gatorcan-backend/models/assignment.go
- gatorcan-backend/models/submission.go
> implemented assignment, submission schema

- gatorcan-backend/DTOs/assignmentDTOs.go
- gatorcan-backend/controllers/assignmentController.go
- gatorcan-backend/controllers/courseController.go
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/main.go
- gatorcan-backend/repositories/assignmentRepository.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/services/assignmentService.go
> implemented repo, service, controller for assignment and defined the routes

- gatorcan-backend/controllers/userController.go
- gatorcan-backend/go.mod
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/services/userService.go
- gatorcan-backend/tests/test_setup.go
- gatorcan-backend/unit_tests/mocks/services.go
- gatorcan-backend/unit_tests/userService_test.go
> #issue 229: Fix/unit tests sprint3 init

- gatorcan-backend/DTOs/assignmentDTOs.go
- gatorcan-backend/DTOs/updateAssignmentDTOs.go
- gatorcan-backend/controllers/assignmentController.go
- gatorcan-backend/errors/assignmentErrors.go
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/main.go
- gatorcan-backend/models/assignment.go
- gatorcan-backend/repositories/assignmentRepository.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/services/assignmentService.go
- gatorcan-backend/services/courseService.go
> #Issue 193: Feature/upload file to assignment endpoint

- gatorcan-backend/controllers/assignmentController.go
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/repositories/assignmentRepository.go
- gatorcan-backend/services/assignmentService.go
> implemented fetching assignments based on course and/ assignment id

- gatorcan-backend/errors/submissionErrors.go
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/repositories/submissionRepository.go
- gatorcan-backend/services/submissionService.go
- gatorcan-backend/unit_tests/assignmentService_test.go
- gatorcan-backend/unit_tests/assignmentsController_test.go
- gatorcan-backend/unit_tests/courseController_test.go
- gatorcan-backend/unit_tests/courseService_test.go
- gatorcan-backend/unit_tests/mocks/repositories.go
- gatorcan-backend/unit_tests/mocks/services.go
- gatorcan-backend/unit_tests/submissionController_test.go
> implemented unit tests for assignments and submission

- gatorcan-frontend/src/components/ChatBox.jsx
- gatorcan-frontend/src/components/ChatBox.test.jsx
- gatorcan-frontend/src/components/Student/Courses/CourseAssignment.jsx
- gatorcan-frontend/src/components/Student/Courses/CourseAssignments.jsx
- gatorcan-frontend/src/components/Student/Courses/CourseAssignments.test.jsx
- gatorcan-frontend/src/components/Student/Courses/CourseChat.jsx
- gatorcan-frontend/src/components/Student/Courses/CourseGrades.test.jsx
- gatorcan-frontend/src/components/Student/Courses/CourseHome.test.jsx
- gatorcan-frontend/src/components/Student/StudentProfile.test.jsx
Closes the following issues:
#203: Assignment Listing and Submission UI
#204: Display a list of available assignments (GET /assignments).
#205: Display list of submitted assignments (GET /assignments/submitted).
#206: Create a file upload form for submitting new assignments (POST /assignments/upload).
#207: Handle success/error messages and form validation.
#208: Write tests for the implemented functionality.
#209: Real-Time Messaging UI for Each Course
#210: Chat window UI scoped to each course.
#211: Message input and display area.
#212: Handle UI states: connected, disconnected, loading.
#213: Write tests to validate implemented functionality.
> Feature/assignment listing+real time UI

- Sprint3.md
> implemented microservice for AI related functionality

- gatorcan-backend/adapters/aiServiceAdapter.go
- gatorcan-backend/controllers/aiserviceController.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/services/aiserviceService.go
> implemented text summarization

- gatorcan-backend/DTOs/submissionDTOs.go
- gatorcan-backend/controllers/submissionController.go
- gatorcan-backend/errors/courseErrors.go
- gatorcan-backend/errors/submissionErrors.go
- gatorcan-backend/interfaces/interfaces.go
- gatorcan-backend/repositories/submissionRepository.go
- gatorcan-backend/routes/userRoutes.go
- gatorcan-backend/services/submissionService.go
> implemented fetching grades for all assigments
